export const TeamMembersList = [
    {
        id:1,
        name: "Batın Özkurt",
        speciality: "Test Engineer",
        mail: "batin@mail.com",
        address: "Tepebaşı/Eskişehir, Turkey",
        github: "https://github.com/batinozkurt",
        linkedin: "https://www.linkedin.com/in/bat%C4%B1n-%C3%B6zkurt-90a568207/",
    },
    {
        id:2,
        name: "Mert Yüksek",
        speciality: "DBMS Manager",
        mail: "mert@mail.com",
        address: "Kazanlı/Mersin, Turkey",
        github: "https://github.com/MertYuksek",
        linkedin: "https://www.linkedin.com/in/mert-y%C3%BCksek-84b62b18a/",
    },
    {
        id:3,
        name: "Mustafa Barış Ege",
        speciality: "Project Manager",
        mail: "boris@mail.com",
        address: "City Center/Karaman, Turkey",
        github: "https://github.com/ML-std",
        linkedin: "https://www.linkedin.com/in/mustafa-baris-ege/",
    },
    {
        id:4,
        name: "Muzaffer Verdil",
        speciality: "Frontend Developer",
        mail: "verdil@mail.com",
        address: "Tepebaşı/Eskişehir, Turkey",
        github: "https://github.com/muzafferverdil",
        linkedin: "https://www.linkedin.com/",
    },
    {
        id:5,
        name: "Taha Talha PINARLI",
        speciality: "Fullstack Developer",
        mail: "ttp@mail.com",
        address: "Odunpazarı/Eskişehir, Turkey",
        github: "https://github.com/tt-p",
        linkedin: "https://www.linkedin.com/in/taha-talha-p%C4%B1narl%C4%B1/",
    },
];