export const TeamMembersList = [
    {
        id:1,
        name: "Batın Özkurt",
        speciality: "DBMS Specialist",
        mail: "batin@mail.com",
        address: "Tepebaşı/Eskişehir, Turkey",
        github: "https://github.com/batinozkurt",
        linkedin: "https://www.linkedin.com/in/bat%C4%B1n-%C3%B6zkurt-90a568207/",
        image: "../info/img/1.png",
    },
    {
        id:2,
        name: "Mert Yüksek",
        speciality: "System Engineer",
        mail: "mert@mail.com",
        address: "Tepebaşı/Eskişehir, Turkey",
        github: "https://github.com/MertYuksek",
        linkedin: "https://www.linkedin.com/in/mert-y%C3%BCksek-84b62b18a/",
        image: "",
    },
    {
        id:3,
        name: "Mustafa Barış Ege",
        speciality: "Android Developer",
        mail: "boris@mail.com",
        address: "Tepebaşı/Eskişehir, Turkey",
        github: "https://github.com/ML-std",
        linkedin: "https://www.linkedin.com/in/mustafa-baris-ege/",
        image: "../info/img/5.png",
    },
    {
        id:4,
        name: "Muzaffer Verdil",
        speciality: "Frontend Developer",
        mail: "verdil@mail.com",
        address: "Tepebaşı/Eskişehir, Turkey",
        github: "https://github.com/muzafferverdil",
        linkedin: "https://www.linkedin.com/",
        image: "../info/img/1.png",
    },
    {
        id:5,
        name: "Taha Talha PINARLI",
        speciality: "Backend Developer",
        mail: "ttp@mail.com",
        address: "Odunpazarı/Eskişehir, Turkey",
        github: "https://github.com/tt-p",
        linkedin: "https://www.linkedin.com/in/taha-talha-p%C4%B1narl%C4%B1/",
        image: "../info/img/1.png",
    },
];